### ISSUE TITLE
Make mapping tables configurable

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#10]
At present, the mapping tables from pixel vectors to camera shapes are fixed. The following configuration options may be added:
- Additional padding around the camera image (default: none). This could be useful for matching a shower image to the fixed size expected by a model if resizing is not preferred, or for constraining images from different cameras to have the same shape. This applies to all telescope types.
- Hexagonal to square pixel conversion method, such as oversampling or warping, to apply (default: uncertain). Each method will require its own parameters, e.g. whether to apply smoothing when oversampling and which technique to use for it. This applies only to telescope types with hexagonal pixels.

**Comment by bryankim96** [comment]
Completed in eddf4e41b4c2d97db041c6cefc8c5e74422abd4a.
