### ISSUE TITLE
Error in pip install --upgrade .

### ISSUE THREAD

**Issue by jonpsy** [ctlearn-project/ctlearn#125]
Hey there,
I'm kinda newbie here so sorry if the issue is misplaced or in the wrong sub. I faced error when trying to setup dl1-data-handler as per the method mentioned in the README.

I already had tensorflow_gpu installed in an environment so I went ahead and just git cloned dl1-data-handler, then I went into the folder and ran pip install --upgrade . 
I got this error 

![Screenshot from 2020-01-30 01-53-10](https://user-images.githubusercontent.com/45007169/73394316-5f3cbb80-4303-11ea-922d-fae556fb159b.png)

**Comment by TjarkMiener** [comment]
Hi @NanuSai! Thanks for opening this issue. The installation via pip and conda is not working at the moment. We should probably update our README. Sorry about that. Please follow the installation instruction in the dl1-data-handler repo and install ctapipe and the dl1-data-handler from source via `python setup.py install`.

**Comment by NanuSai** [comment]
If it's not a problem, may I update the README.md notifying this issue?
