### ISSUE TITLE
CTLearn Zenodo's record unaccessible ?

### ISSUE THREAD

**Issue by vuillaut** [ctlearn-project/ctlearn#184]
Hi !

**Describe the bug**

The CTLearn Zenodo record is not accessible:
https://zenodo.org/records/5947837

but Zenodo other records are.

Any idea what is happening there?

**Comment by TjarkMiener** [comment]
Thanks for reporting @vuillaut! I have no idea what is going on. I will contact [info@zenodo.org](mailto:info@zenodo.org) as advised [here](https://github.com/zenodo/zenodo/issues/1660).

**Comment by TjarkMiener** [comment]
The zenodo team was able to fix the issue. Attaching their reply for the sake of completeness.

---------------------
Dear CTLearn Team,

We have fixed this record for you. Thank you for flagging this issue as we were able to fix 15 other records which had also gotten into this state

Please let me know if there is anything else I can help you with.

Best regards,
Carlin
Zenodo Support
https://zenodo.org/

**Comment by vuillaut** [comment]
That was fast!
Thanks.
