### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#25]
Ensure that the Readme is up to date with all the changes for v0.2.0. Update the version number in setup.py.

Create a directory called deprecated in the models directory and move all the unused models there. The unused models are all but cnn_rnn.py, single_tel.py, and variable_input model.py. The deprecated models will be removed in the next release if not used by then.

Remove the unnecessary ctalearn/ctalearn/scripts directory. Put train.py and predict.py in ctalearn/ctalearn/. (These will be merged into a single module, see #22.)

Create a ctalearn/config directory and move example_config.ini there. This is also where config files for standard networks will go.

Create a ctalearn/scripts directory and move plot_classifer_value.py, plot_roc_curves.py, visualize_bounding_boxes.py, train_configurations.py, and test_metadata.py there.

Remove plot_gpu_util.py as it is not relevant for using ctalearn.

Move ctalearn/misc/images/ to ctalearn/images and delete the ctalearn/misc/ directory.

**Comment by bryankim96** [comment]
All complete except README + documentation + updating version number + package name.

**Comment by bryankim96** [comment]
Version number and package name updated in 0499e78f4d9215fd70ccf68773a1521bc54da1f6 and b1cad378d96671a5c1af32fe7c4b140e3f5b7644.

**Comment by aribrill** [comment]
The Readme is now up to date with CTLearn v0.2.0.
