### ISSUE TITLE
Make package compatible with ConfigObj

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#33]
Example configuration files are currently being stored in two locations, ctalearn/config and ctalearn/ctalearn/config. Determine which location is better and merge the two directories. 

The script train_configurations.py for automating hyperparameter searches relies heavily on the ConfigParser file format. Update it to match the new configuration file format.

As currently written, run_models.py requires an additional command line argument for the config spec. This is unnecessary because the configuration spec won't change from run to run. Instead hardcode the path to the config spec. See f4a420f431ebaf83bf107939c2bdb9bcb37547e5 and ffcfda8f2761ee512c9d6e18b490eacd7763b57e for a good way to do this.

Update variable_input_model.py to use the new configuration option names.

Add a comment in example_config.conf to indicate that the allowed values and types for each option are identified in config_spec.ini.

**Comment by bryankim96** [comment]
All changes except updating variable_input_model are implemented. The rest of the changes in this issue are no longer required with the changes pending for #36 .
