### ISSUE TITLE
Append CTLearn version to the copy of the configuration file generated for each training

### ISSUE THREAD

**Issue by nietootein** [ctlearn-project/ctlearn#35]
In order to ensure the reproducibility of each training run a copy of the parsed config file is stored along with the rest of training outputs. Ideally, such reproducibility should not depend on the version of the code that was used for training, although this dependency might be present during the pre-release development phase. Therefore, appending the code version to the copy of the configuration file may be helpful.

**Comment by TjarkMiener** [comment]
@nietootein Did you thought of a comment or an argument for the code version in the configuration file?
