### ISSUE TITLE
Replace ConfigObj config file format with YAML

### ISSUE THREAD

**Issue by bryankim96** [ctlearn-project/ctlearn#36]
train_configurations.py script must be rewritten to use YAML-formatted config file. Example config file needs to be re-written. Any relevant value-checking/exceptions must be added. Loading/reading config in run_model.py must also be refactored. Variable input model must be updated to match new configuration option names.

The standard pattern for loading configuration options is as follows: The settings which are used for each part of the pipeline/each class (DataLoader, DataProcessor, ImageMapper) should be collected in separate sections within the config file and read in as a complete dictionary. This dictionary is then unpacked directly into the constructor for the corresponding class to pass all desired settings(which should all be implemented as keyword arguments).

**Comment by aribrill** [comment]
The Basic, CNN-RNN, and Single Tel models must be updated to use any new configuration names as well.
