### ISSUE TITLE
Telescope IDs are not unique, causing critical error

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#39]
The current design of DataLoader relies on the tel_id parameter as a unique key to index the telescopes, making checks that each tel_id corresponds to a telescope of the correct type. However, this assumption is invalid. The telescope IDs in the MLProto dataset are not unique. The conflict is with SST1. IDs 1-4 are used by both SST1 and LST; 5-29 by SST1 and MSTF; and 30-33 by SST1 and MSTN.

For example, tel_id 1 is assigned to SST1, so when running a model using LST data, run_model.py crashes with the following output:
```
Traceback (most recent call last):
  File "ctlearn/ctlearn/run_model.py", line 456, in <module>
    run_model(config, mode=args.mode, debug=args.debug, log_to_file=args.log_to_file)
  File "ctlearn/ctlearn/run_model.py", line 130, in run_model
    **data_loading_settings)
  File "/home/shevek/software/anaconda3/envs/testing-brill/lib/python3.6/site-packages/ctlearn/data_loading.py", line 125, in __init__
    self._select_telescopes(selected_tel_type, tel_ids=selected_tel_ids)
  File "/home/shevek/software/anaconda3/envs/testing-brill/lib/python3.6/site-packages/ctlearn/data_loading.py", line 366, in _select_telescopes
    raise ValueError("Selected tel id {} is of wrong tel type {}.".format(tel_id, all_tel_ids[tel_id]))
ValueError: Selected tel id 1 is of wrong tel type LST.
```

The treatment of tel_ids in DataLoader needs to rewritten to accommodate this. The best way may be to move away from integer tel_ids, so that the overall tel_id could be either a string of the telescope type concatenated with the tel_id number, perhaps with a separator, or a tuple of (tel_type, tel_id).

**Comment by aribrill** [comment]
I'll work on this now in the interest of time. The solution I will take is to use (tel_type, tel_id) tuples as unique identifiers when needed in HDF5DataLoader. This problem also impacts the assignment of tel_ids to telescope indices in the event table, so I will fix that as well. 

However, we should have a future discussion about whether this is the correct behavior expected from the ImageExtractor data format and whether there's anything we can do at that level to make things easier.

**Comment by aribrill** [comment]
Closed by 4b5e8905ba59b5af321beef3fda2fbd208f93c81.

**Comment by bryankim96** [comment]
Thanks Ari, sorry I couldn't get to it sooner. If this is solely an issue with the SST1, I also wonder if it is intentional or a bug. It seems like if it was intentional they would have made the SST1 tel ids only overlap with other SSTs, not all different types of telescope.

**Comment by bryankim96** [comment]
I see, good catch. I think we probsbly decided to use 1 byte based on the expected total number of telescopes in the array (LST, MST, SST) without considering the additional count due to the number of types. It is unfortunate that we will have to add logic for this special case when it is clearly not intended. I wonder if it would be possible to instead reprocess the files with a simple pytables python script to revise that column. I don't know how much time it would take to reprocess the entire dataset, but it would have the benefit of avoiding adding a non-obvious special case and will also make the dataset tel ids agree with those in the original simulations, which could be expected/important for users.

**Comment by aribrill** [comment]
The permanent solution is definitely to fix it in the next processing of the dataset. Since the ProtoML dataset has already been made available, though, I suppose it's too late to change that. For now, maybe the simplest thing to do is to add 255 to the tel_id for SST1s if the tel_id is less than 220. This would then make it unnecessary to use tel_type as an additional index, so we could actually undo some of the changes I made earlier in response to this issue (since having repeated tel_ids is clearly just due to a bug and theoretically won't reoccur in the future).

**Comment by bryankim96** [comment]
That sounds like the cleanest solution on our side. As far as the dataset goes, I feel like it might not be unreasonable to revise the dataset and reupload/update the wiki page, even though ProtoML was technically "officially released". I suspect no one (or few enough people) have downloaded it so far, so a revision might not be very disruptive (especially if it reduces later confusion by people who chose to use the dataset but not, for example, ctlearn). The alternative, I guess, is writing a very clear note on the wiki warning about this issue.

**Comment by aribrill** [comment]
I've inserted the temporary fix mentioned above and restored using tel_id as the unique telescope index, keeping the other ancillary fixes and simplifications made to DataLoader.
