### ISSUE TITLE
Clean up input_fn in run_model.py

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#41]
Use dictionary unpacking to pass in settings instead of passing the dictionary directly. This will provide a convenient way to provide default arguments, making it easier to have optional data input settings. At least one options that is currently configurable should be hardcoded, that is whether to use dataset.map() - this is already constrained by the choice of data format. Also, investigate whether it's worth making whether to prefetch a configurable option or if there's a best practice for it that could just be hardcoded.

**Comment by bryankim96** [comment]
I think it is safe to hardcode prefetch. Also agree that the map option should be removed. Another thing to be examined is the duplication of shuffling in the data loading and the tf.Datasets.
