### ISSUE TITLE
Benchmark in peak_times channel mode

### ISSUE THREAD

**Issue by Jsevillamol** [ctlearn-project/ctlearn#53]
| input_type | tel_type | auroc      | 
|------------|----------|------------| 
| array      | LST      | 0.8286985  | 
| array      | MSTF     | 0.89471704 | 
| array      | MSTN     | 0.9177482  | 
| array      | MSTS     | 0.91144246 | 
| array      | SST1     | 0.8937345  | 
| array      | SSTA     | 0.86309916 | 
| array      | SSTC     | 0.90838027 | 
| single_tel | LST      | 0.7877764  | 
| single_tel | MSTF     | 0.8263566  | 
| single_tel | MSTN     | 0.8663868  | 
| single_tel | MSTS     | 0.866212   | 
| single_tel | SST1     | 0.85580283 | 
| single_tel | SSTA     | 0.8018345  | 
| single_tel | SSTC     | 0.80345446 |

**Comment by aribrill** [comment]
Do these results correspond to the analysis with the peak times channel enabled or disabled? They seem consistent with the charges only results.

**Comment by Jsevillamol** [comment]
@aribrill these correspond to peak times enabled. It seems that the additional channel does not enable any kind of improvement
