### ISSUE TITLE
Load and process metadata better in DataLoader

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#57]
DataLoader should load and return metadata better in several ways.

1. `DataLoader._load_metadata()` is long, complex, and poorly commented. Refactor it into smaller methods that each perform a particular task.
2. Remove the expensive step of calculating the image mins and maxes when normalization isn't being used. To do so, remove the `DataLoader.add_data_processor()` method and enforce the DataProcessor to be defined at initialization. Create a new method `DataProcessor.add_image_mins()` so that the image mins can be calculated only if needed (that is, `if self.data_processor.normalization is not None`). This should greatly speed up data loading when no normalization is needed and moves a possibly confusing element of the API out of sight of the user.
3. Many of the metadata parameter names are ambiguous and need to be made consistent.
a. `num_classes` is the length of `particle_ids`. These should be changed to either `num_classes` and `classes` or `num_particle_ids` and `particle_ids`.
b. `selected_telescopes_types` should be changed to reflect #54.
c. `num_telescopes` is actually the number of selected telescopes, not the number of telescopes. For clarification, `telescopes` could be renamed to `total_telescopes`. Then the parameters would be `total_telescopes` (currently `telescopes`), `num_total_telescopes` (new), `selected_telescopes`, and `num_selected_telescopes` (currently `num_telescopes`).
d. `num_events_by_particle_id` and `num_images_by_particle_id` are ambiguous whether they refer to the data before or after cuts. In fact, that is currently inconsistent in the actual implementation (#48). The metadata should contain both, that is, four parameters total for the events/images before/after cuts. This is needed for accurate logging and to calculate signal efficiency.
e. `class_to_name` is also called `label_to_name` internally, which is confusing. As a compromise, it could be changed everywhere to `class_label_to_name`, or either "class" or "label" could be chosen.

**Comment by Jsevillamol** [comment]
- [ ] Refactor `DataLoader._load_metadata()`
- [ ] Remove minmax calculation when not needed
- [ ] Make names consistent

**Comment by bryankim96** [comment]
The main issue I can see with that idea is that if we want the user to be able to make full use all of the constructor arguments/settings of DataProcessor, but instantiation of a DataProcessor is always done in a DataLoader, we have to pass all DataProcessor settings through the DataLoader constructor, which seems clunky and redundant. Unless there's a better approach I'm missing?

**Comment by bryankim96** [comment]
That seems like the right idea. It is good to keep the interface of DataProcessor as generic as possible to, for example, allow it to be used without DataLoader (i.e. by passing in pre-computed normalization statistics which you already have for your data).

**Comment by Jsevillamol** [comment]
Why are we computing the image max charges at all?
Shouldn't we just get rid of that?

**Comment by Jsevillamol** [comment]
@bryankim96 that is what I've come to realize would be the logical way of setting up things - I was confused about the flow of things when I wrote my initial response. I have submitted a commit 1bac6dcb0f2a585a80672fb390ab77f7213a50e1 with the proposed change if you want to take a look.

**Comment by Jsevillamol** [comment]
Re: max charges. I we see a potential use let's leave it for now, and maybe later implement the under demand statistics you propose.

**Comment by Jsevillamol** [comment]
@aribrill can you take care of implementing the changes remaining in this issue (about #54 terminology) when you implement #54 ?

**Comment by aribrill** [comment]
Yes, can do. I've reassigned the remaining part of the issue to myself.

**Comment by aribrill** [comment]
Also pending #54, change the the structure of the field `num_images_after_cuts_by_class_name` to support multiple telescopes and rename it to `num_images_after_cuts_by_tel_and_class_name`.
