### ISSUE TITLE
Add example configuration using `variable input model`

### ISSUE THREAD

**Issue by Jsevillamol** [ctlearn-project/ctlearn#70]
I have had trouble getting the `variable input model` to execute. In the current repository, we have examples of `single tel` and `cnn_rnn` config files ready for execution, but none for `variable_input_model`.

I would like to have one as a reference for testing.

**Comment by aribrill** [comment]
The attached config file works to train `variable_input_model` using the CTLearn version in master. The settings are those in the example config file.
[variable_input_config.yml.txt](https://github.com/ctlearn-project/ctlearn/files/2457730/variable_input_config.yml.txt)
