### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by nietootein** [ctlearn-project/ctlearn#87]
The OpenAstronomy team draw our attention to the lack of guidelines for potential contributors (see
[here](https://github.com/OpenAstronomy/openastronomy.github.io/pull/208)). This could be solved by pushing a CONTRIBUTING.md file to the repository.

**Comment by bryankim96** [comment]
I feel that ctapipe probably offers a good example that we can follow in terms of contributing/development guidelines. Maybe we could base our contributing guidelines loosely on their guidelines here:

https://cta-observatory.github.io/ctapipe/development/index.html

**Comment by aribrill** [comment]
Closed by #90.
