### ISSUE TITLE
Regarding the Installation

### ISSUE THREAD

**Issue by irahulcse** [ctlearn-project/ctlearn#91]
After cloning and installing the Anaconda, I am not able to run the command like `conda env create -f </installation/path>/ctlearn/environment-<MODE>.yml`
It is showing me the error? Pls have a look to it.
![screenshot from 2019-03-03 09-48-26](https://user-images.githubusercontent.com/34218254/53690929-d12a1f00-3d99-11e9-9d1c-a7f4f4aa42bc.png)

**Comment by aribrill** [comment]
This error message means the environment file doesn't exist / wasn't found (see [here](https://github.com/conda/conda/issues/5681)). Try double checking that the path is right.

**Comment by TjarkMiener** [comment]
I see you are in your Downloads folder. If you have downloaded the zip, you need to unzip and change .../ctlearn/... to .../ctlearn-master/... in your path! However, I would recommend you to clone the repo.

**Comment by aribrill** [comment]
@irahulcse I will close this issue now, but feel free to re-open it if you still have problems installing the code.
