### ISSUE TITLE
Update TF version to >= 1.12

### ISSUE THREAD

**Issue by nietootein** [ctlearn-project/ctlearn#98]
An implementation of the Keras API is available in TensorFlow from version 1.12 (see [here](https://www.tensorflow.org/guide/keras)). It may be useful to update our current TF version to the latest stable release so we can make use of this new feature.

**Comment by MoltenMuffins** [comment]
Hello there! I'm looking to contribute to the CTLearn project as part of my application for the project "Hexagonal Convolution" for GSOC. May I work on this issue?

**Comment by nietootein** [comment]
Hello @MoltenMuffins!

Thanks for your offer to take over this issue. This is a high priority one we are working on right now, and it's close to be solved.

**Comment by aribrill** [comment]
Closed by 60335ad9899741f1045e4ffa8da918d6ef127229
